apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: tp1-gitops
    count: 3
images:
  - name: ghcr.io/kousay-jebir/tp1-gitops
    newTag: wrongtag
